import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, expect, it } from 'vitest';
import { createFakeModel } from '@cofold/agents/testing';
import type { FakeModel } from '@cofold/agents/testing';
import type { ModelAdapter } from '@cofold/agents';
import { localPath } from '@ahpd/sdk';
import type { Bag, MessageAttachment } from '@ahpd/sdk';
import { createHost } from '../../sdk/src/host.js';
import { fileSessions } from '../../sdk/src/sessions.js';
import { cofoldAgent } from '../src/index.js';
import type { Peer } from '../../sdk/src/types/rpc.js';
import type { HostTool } from '../../sdk/src/types/host.js';

/*
 * A cofold turn reads its message's attachments.
 *
 * The host writes what a client pasted to a file and the message names the path
 * - decision `an-attachments-bytes-are-written-to-disk-and-the-message-names-
 * the-file` - and `partsOf` decides what each attachment is, within the limits
 * every backend shares. What this backend adds is where the parts go: cofold's
 * run takes its input as a string or as content parts, so a message with
 * attachments is started as parts and one without stays the string it always
 * was.
 *
 * A picture is sent as an image only to a model that takes one, asked off the
 * adapter the turn resolves rather than assumed: an image part to a model
 * without the feature throws, and the message is stored, so every later turn of
 * the conversation would fail on it too.
 *
 * The same for a message the queue holds and one that steers the running turn.
 */

const bag = (value: unknown): Bag => (typeof value === 'object' && value !== null ? value as Bag : {});

function peer(): Peer & { notes: { method: string; params: unknown }[] } {
  const notes: { method: string; params: unknown }[] = [];
  return {
    notes,
    send: () => {},
    notify: (method, params) => notes.push({ method, params }),
    request: async () => ({}),
    answered: () => {},
    close: () => {},
  };
}

/**
 * Let the run's work finish, up to a point.
 *
 * `partsOf` reads real bytes off the disk, so a turn here settles over a few
 * turns of the event loop rather than on the first one.
 */
const until = async (check: () => boolean, times = 2000): Promise<void> => {
  for (let i = 0; i < times; i++) {
    if (check()) return;
    await new Promise((r) => { setTimeout(r, 0); });
  }
};

/** A fixed number of turns of the event loop, for work with nothing to watch. */
const settle = async (times = 200): Promise<void> => {
  for (let i = 0; i < times; i++) await new Promise((r) => { setTimeout(r, 0); });
};

type Note = { channel: string; action: Record<string, unknown> };

const actions = (p: ReturnType<typeof peer>, channel: string): Note[] => p.notes
  .filter((n) => n.method === 'action')
  .map((n) => n.params as Note)
  .filter((e) => e.channel === channel);

/** The attachments the turn at `at` was accepted with, as the host settled them. */
const settled = (p: ReturnType<typeof peer>, chatUri: string, at = 0): Bag[] => {
  const started = actions(p, chatUri).filter((e) => e.action.type === 'chat/turnStarted')[at];
  const held = bag(started?.action.message).attachments;
  return Array.isArray(held) ? held as Bag[] : [];
};

/**
 * The parts of the newest user message a request carries.
 *
 * The newest and not the first: a request carries the conversation, so a
 * later turn's own message is the last one in it - and a steered message is
 * one more user message after the turn's own.
 */
const input = (model: FakeModel, at = 0): Bag[] => {
  const said = model.requests[at]?.messages.filter((one) => one.role === 'user') ?? [];
  // A part is cofold's own union, which reads like the one the protocol
  // declares: the shapes are the same, the names are not.
  return (said.at(-1)?.parts ?? []) as unknown as Bag[];
};

/** The lines of the one reference block, which is where a named attachment goes. */
const references = (model: FakeModel, at = 0): string[] => {
  const block = input(model, at).map((one) => String(one.text ?? '')).find((one) => one.startsWith('The user provided'));
  return (block ?? '').split('\n').slice(1);
};

const image = (type = 'image/png'): Bag => ({ type: 'image', mimeType: type, data: PNG.toString('base64') });

/** A PNG's first bytes. Nothing here decodes it, so a header is a picture. */
const PNG = Buffer.from('89504e470d0a1a0a0000000d49484452000000010000000108060000001f15c489', 'hex');

const READ_ONLY = '(read-only snapshot, do not edit this file)';

/** Everything under a real folder, removed once the case is done. */
const made: string[] = [];
afterEach(() => {
  for (const dir of made) rmSync(dir, { recursive: true, force: true });
  made.length = 0;
});

const wrote = (name: string, bytes: Buffer | string): string => {
  const path = join(made[0]!, name);
  writeFileSync(path, bytes);
  return path;
};

/**
 * An attachment as a client sends it.
 *
 * The protocol declares its variants as a `const enum`, whose members name
 * themselves as words but are not values anything imports, so a test writes the
 * word and this is where it becomes the type the session is handed.
 */
const carried = (one: Bag): MessageAttachment => one as unknown as MessageAttachment;

/** What a client pasted: bytes the host writes to a file of its own. */
const pasted = (label: string, contentType: string, bytes: Buffer): MessageAttachment =>
  carried({ type: 'embeddedResource', label, contentType, data: bytes.toString('base64') });

/** What a client picked: a file already on this host, which nothing copies. */
const picked = (path: string, label: string, contentType: string): MessageAttachment =>
  carried({ type: 'resource', uri: `file://${path}`, label, contentType });

/** A connected client with one cofold session, whose attachments are real files. */
async function talking(model: ModelAdapter, tools: HostTool[] = []) {
  const path = mkdtempSync(join(tmpdir(), 'ahpd-cofold-attach-'));
  made.push(path);
  const host = createHost({
    path,
    // The store answers `attachmentsDir`, which is the one thing that makes a
    // pasted picture a file the message names rather than bytes it carries.
    sessions: fileSessions({ dir: join(path, 'sessions') }),
    agents: [cofoldAgent({ adapter: model, memory: true })],
    ...(tools.length > 0 ? { tools } : {}),
  });
  const p = peer();
  const client = host.accept(p);
  await client.handle({
    method: 'initialize',
    params: { clientId: 'probe', protocolVersions: ['0.9.0'], initialSubscriptions: ['ahp-root://'] },
  });
  const uri = 'ahp-session:/one';
  const chatUri = 'ahp-chat:/one';
  await client.handle({ method: 'createSession', params: { channel: uri, provider: 'cofold' } });
  await client.handle({ method: 'subscribe', params: { channel: uri } });
  await client.handle({ method: 'subscribe', params: { channel: chatUri } });
  return { host, client, peer: p, uri, chatUri };
}

/** One action dispatched by the client, awaited: the host writes files first. */
const send = (client: Awaited<ReturnType<typeof talking>>['client'], channel: string, action: Bag) =>
  client.handle({ method: 'dispatchAction', params: { channel, action } });

/**
 * Wait until the dispatch this client sent before it has been applied.
 *
 * A dispatch is a notification: the host answers it and applies it later, and
 * a message whose attachments have to be written is applied after the write.
 * A later dispatch from the same client goes behind one that is still waiting,
 * so this sends a draft nobody is using and waits for the host to say it took
 * it - which is what says the message before it has landed.
 */
const applied = async (
  client: Awaited<ReturnType<typeof talking>>['client'],
  p: ReturnType<typeof peer>,
  chatUri: string,
): Promise<void> => {
  const drafts = (): number => actions(p, chatUri).filter((e) => e.action.type === 'chat/draftChanged').length;
  const before = drafts();
  // A different draft each time: a session keeps the one it was last sent, and
  // the same one again is a no-op that is never echoed.
  await send(client, chatUri, { type: 'chat/draftChanged', draft: { text: crypto.randomUUID() } });
  await until(() => drafts() > before);
};

it('sends a message with nothing attached as the plain text it always was', async () => {
  const model = createFakeModel({ script: [{ text: 'ok' }], stream: true });
  const { client, chatUri } = await talking(model);
  await send(client, chatUri, { type: 'chat/turnStarted', turnId: 't1', message: { text: 'hi' } });
  await until(() => model.requests.length > 0);

  expect(input(model)).toEqual([{ type: 'text', text: 'hi' }]);
});

it('sends a pasted image as an image part to a model that takes images', async () => {
  const model = createFakeModel({ script: [{ text: 'ok' }], stream: true, features: { images: true } });
  const { client, peer: p, chatUri } = await talking(model);
  await send(client, chatUri, {
    type: 'chat/turnStarted',
    turnId: 't1',
    message: { text: 'look', attachments: [pasted('shot.png', 'image/png', PNG)] },
  });
  await until(() => model.requests.length > 0);

  // The picture itself, not the path to it: the bytes went to a file, and the
  // model is sent what the file holds.
  expect(input(model)).toEqual([{ type: 'text', text: 'look' }, image()]);
  // And the turn a client reads back names the file the host wrote.
  expect(localPath(String(settled(p, chatUri)[0]?.uri))).toMatch(/-shot\.png$/);
});

it('names that image by path when the model takes none', async () => {
  const model = createFakeModel({ script: [{ text: 'ok' }], stream: true });
  const { client, peer: p, chatUri } = await talking(model);
  await send(client, chatUri, {
    type: 'chat/turnStarted',
    turnId: 't1',
    message: { text: 'look', attachments: [pasted('shot.png', 'image/png', PNG)] },
  });
  await until(() => model.requests.length > 0);

  const written = localPath(String(settled(p, chatUri)[0]?.uri));
  expect(input(model)).toEqual([
    { type: 'text', text: 'look' },
    { type: 'text', text: `The user provided the following references:\n- ${written} ${READ_ONLY}` },
  ]);
});

it('inlines a pasted text, which the host wrote for this message', async () => {
  const model = createFakeModel({ script: [{ text: 'ok' }], stream: true });
  const { client, chatUri } = await talking(model);
  await send(client, chatUri, {
    type: 'chat/turnStarted',
    turnId: 't1',
    message: { text: 'read this', attachments: [pasted('note.txt', 'text/plain', Buffer.from('one\ntwo\n'))] },
  });
  await until(() => model.requests.length > 0);

  expect(input(model)).toEqual([
    { type: 'text', text: 'read this' },
    { type: 'text', text: 'note.txt (lines 1-2):\n```\none\ntwo\n```' },
  ]);
});

it('names a file somebody picked, which is one they work in rather than paste', async () => {
  const model = createFakeModel({ script: [{ text: 'ok' }], stream: true });
  const { client, chatUri } = await talking(model);
  const mine = wrote('picked.txt', 'mine\n');
  await send(client, chatUri, {
    type: 'chat/turnStarted',
    turnId: 't1',
    message: { text: 'look at this', attachments: [picked(mine, 'picked.txt', 'text/plain')] },
  });
  await until(() => model.requests.length > 0);

  // Small and textual, and still named: only a file this host wrote is the
  // message's own, and a copy of somebody's own file is not what they attached.
  expect(references(model)).toEqual([`- ${mine}`]);
});

it('holds a queued message\'s attachments and sends them when its turn comes', async () => {
  const model = createFakeModel({
    script: [{ text: 'first' }, { text: 'second' }],
    stream: true,
    features: { images: true },
  });
  const { client, chatUri } = await talking(model);
  await send(client, chatUri, { type: 'chat/turnStarted', turnId: 't1', message: { text: 'first' } });
  await until(() => model.requests.length === 1);

  await send(client, chatUri, {
    type: 'chat/pendingMessageSet',
    kind: 'queued',
    id: 'q1',
    message: { text: 'second', attachments: [pasted('shot.png', 'image/png', PNG)] },
  });
  // Waiting behind the turn, so only the first has reached the model.
  expect(model.requests).toHaveLength(1);

  await until(() => model.requests.length === 2);
  expect(input(model, 1)).toEqual([{ type: 'text', text: 'second' }, image()]);
});

it('steers the running turn with the parts of what was sent', async () => {
  /*
   * Two calls that wait, so the turn is held open across the correction.
   *
   * A correction carrying an attachment reaches the run in two steps, and
   * neither can be watched: the host writes the pasted bytes to a file before
   * the message is applied - which is what `applied` waits for - and the
   * session then reads those bytes back off the disk. So the turn is held
   * across both, by calls this test releases rather than by a clock, and the
   * correction is read on the model the turn is already running.
   */
  const waiting: (() => void)[] = [];
  const tool: HostTool = {
    definition: {
      name: 'lookup',
      title: 'Look something up',
      description: 'Looks a word up.',
      inputSchema: { type: 'object', properties: {} },
    },
    run: () => new Promise<string>((resolve) => { waiting.push(() => resolve('found x')); }),
  };
  const model = createFakeModel({
    script: [
      { toolCalls: [{ name: 'lookup', input: {} }] },
      { toolCalls: [{ name: 'lookup', input: {} }] },
      { text: 'done' },
    ],
    stream: true,
    features: { images: true },
  });
  const { client, peer: p, chatUri } = await talking(model, [tool]);
  await send(client, chatUri, { type: 'chat/turnStarted', turnId: 't1', message: { text: 'first' } });
  await until(() => waiting.length === 1);

  await send(client, chatUri, {
    type: 'chat/pendingMessageSet',
    kind: 'steering',
    id: 's1',
    message: { text: 'actually', attachments: [pasted('shot.png', 'image/png', PNG)] },
  });
  await applied(client, p, chatUri);
  // The bytes come off the disk on their own schedule, and nothing on the wire
  // says when. The turn is held throughout, so this wait costs the run
  // nothing: a correction read later than this one is still read well before
  // the turn ends, on the step after the one below - which is why the
  // assertion is on the last request rather than the next one.
  await settle();

  waiting[0]?.();
  await until(() => model.requests.length === 2);
  waiting[1]?.();
  await until(() => model.requests.length === 3);

  // The turn's own message went as it always did, and the correction was read
  // the way that message is: the picture as a picture, on the model the turn
  // is already running.
  expect(input(model, 0)).toEqual([{ type: 'text', text: 'first' }]);
  expect(input(model, 2)).toEqual([{ type: 'text', text: 'actually' }, image()]);
});
