import { lstat, open } from 'node:fs/promises';
import { extname } from 'node:path';
import { localPath } from './fileuri.js';
import type { Bag } from './types/common.js';
import type { MessageAttachment } from './types/session.js';

/*
 * A message's attachments, as the parts a backend sends.
 *
 * One helper, so every backend makes the same decision about the same
 * attachment and one limit moves for all of them: a pasted screenshot arrives
 * as an image, pasted text arrives as the text, and everything else is named by
 * the path the host wrote it to - decisions
 * `a-pasted-image-goes-as-an-image-when-it-fits` and
 * `pasted-text-is-inlined-up-to-64-kib`.
 *
 * What a backend does with a part is its own: Claude wants a base64 image
 * source, ACP an image block, pi its `images` list. What is decided here is
 * only which of the three a given attachment is, so that decision is made once.
 */

/**
 * The key an attachment a host wrote for a message carries.
 *
 * Its presence is what says a file is the message's own - a copy of something
 * pasted, or of a buffer a client had unsaved - rather than a file somebody
 * works in, which is named by path and left for the model to read.
 */
export const SNAPSHOT_TAG = 'vscode.agentHost.snapshotAttachment';

/** The largest image sent as an image, in bytes. */
const IMAGE_LIMIT = 5 * 1024 * 1024;

/** The largest text inlined into the message, in bytes. */
const TEXT_LIMIT = 64 * 1024;

/** The four types sent as an image, which are the four Claude takes. */
const IMAGE_TYPES = new Set(['image/jpeg', 'image/png', 'image/gif', 'image/webp']);

/** What a file's own name says it is, where nothing else says. */
const IMAGE_EXTENSIONS: Record<string, string> = {
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.png': 'image/png',
  '.gif': 'image/gif',
  '.webp': 'image/webp',
};

/** The note a client's snapshot carries, in the reference block. */
const READ_ONLY = '(read-only snapshot, do not edit this file)';

/** One piece of a message, as a backend sends it. */
export type Part =
  | { type: 'text'; text: string }
  | { type: 'image'; mimeType: string; data: string };

/** What a backend can take beyond the text, and what a message is turned into. */
export interface PartOptions {
  /** Whether the model takes an image at all. */
  images: boolean;
}

/**
 * A message's text and attachments, as the parts to send.
 *
 * The text comes first, always, so a message with nothing attached is the
 * single text part every backend already sends. After it, in the order the
 * client attached them, whatever each attachment is: an image, an inlined text,
 * or a line in the one reference block at the end.
 */
export async function partsOf(
  text: string,
  attachments: MessageAttachment[] | undefined,
  options: PartOptions,
): Promise<Part[]> {
  const parts: Part[] = [{ type: 'text', text }];
  const references: string[] = [];
  for (const one of attachments ?? []) {
    const part = await partOf(one, options);
    if (part === undefined) references.push(referenceFor(one));
    else parts.push(part);
  }
  if (references.length > 0) {
    const lines = ['The user provided the following references:', ...references.map((one) => `- ${one}`)];
    parts.push({ type: 'text', text: lines.join('\n') });
  }
  return parts;
}

/**
 * One attachment as a part of its own, or nothing where it is named instead.
 *
 * Nothing means the reference block: a file the model should open itself, an
 * image too large or of a kind it will not take, and the two attachments that
 * name something rather than carry it - a chat, and a set of annotations.
 */
async function partOf(value: unknown, options: PartOptions): Promise<Part | undefined> {
  const one = bag(value);
  if (one.type === 'simple') {
    // What the producer wrote for the model, which is the whole of it.
    const written = typeof one.modelRepresentation === 'string' ? one.modelRepresentation : '';
    return written === '' ? undefined : { type: 'text', text: written };
  }
  if (one.type === 'resource') {
    const uri = typeof one.uri === 'string' ? one.uri : '';
    // Only a file is read here. Anything else names something this host does
    // not serve, and a client's own reading of it is not this host's to do.
    if (!uri.startsWith('file://')) return undefined;
    const path = localPath(uri);
    const found = await lstat(path).catch(() => undefined);
    // A directory, a device, a pipe or a link: read, any of them is either
    // nothing or forever, so each is named and left alone.
    if (found === undefined || !found.isFile()) return undefined;
    const type = typeFor(one, path);
    if (options.images && IMAGE_TYPES.has(type)) {
      const bytes = await readUpTo(path, IMAGE_LIMIT);
      return bytes === undefined ? undefined : { type: 'image', mimeType: type, data: bytes.toString('base64') };
    }
    /*
     * Inlined only where the host wrote the file for this message. A file in
     * the workspace is the one somebody is working in: a copy of it in the
     * prompt is a copy the model may edit in its head and never on disk.
     */
    if (isSnapshot(one) && isTextual(type)) {
      const bytes = await readUpTo(path, TEXT_LIMIT);
      return bytes === undefined ? undefined : { type: 'text', text: fenced(labelOf(one), bytes.toString('utf8')) };
    }
    return undefined;
  }
  if (one.type === 'embeddedResource') {
    // Never written: this is a host whose write of it failed, or a backend
    // being handed a message by something that is not a host at all.
    const type = typeof one.contentType === 'string' ? one.contentType : '';
    const bytes = Buffer.from(typeof one.data === 'string' ? one.data : '', 'base64');
    if (options.images && IMAGE_TYPES.has(type) && bytes.length <= IMAGE_LIMIT) {
      return { type: 'image', mimeType: type, data: bytes.toString('base64') };
    }
    if (isTextual(type) && bytes.length <= TEXT_LIMIT) {
      return { type: 'text', text: fenced(labelOf(one), bytes.toString('utf8')) };
    }
    return undefined;
  }
  return undefined;
}

/**
 * One line of the reference block: what the attachment is, and where.
 *
 * A file is named by its path, which is what the model's own tools take, with
 * the line a selection starts at - a person's `:12` - and the note that says
 * the file is a snapshot of something pasted rather than a file to edit.
 * Anything that names no file is named by its label, which is all it has.
 */
function referenceFor(value: unknown): string {
  const one = bag(value);
  if (one.type !== 'resource') return labelOf(one);
  const uri = typeof one.uri === 'string' ? one.uri : '';
  const named = uri.startsWith('file://') ? localPath(uri) : uri;
  return `${named}${selectionOf(one)}${isSnapshot(one) ? ` ${READ_ONLY}` : ''}`;
}

/**
 * One file's bytes, or nothing where it is too large to send.
 *
 * Bounded rather than read whole and measured after: the size `lstat` gave is
 * a moment old, and a file still being written is read here up to one byte past
 * what would be sent and named instead - which is the file it is now.
 */
async function readUpTo(path: string, limit: number): Promise<Buffer | undefined> {
  const file = await open(path, 'r').catch(() => undefined);
  if (file === undefined) return undefined;
  try {
    const buffer = Buffer.allocUnsafe(limit + 1);
    const done = await file.read(buffer, 0, limit + 1, 0).catch(() => undefined);
    if (done === undefined || done.bytesRead > limit) return undefined;
    return buffer.subarray(0, done.bytesRead);
  } finally {
    await file.close().catch(() => undefined);
  }
}

/** A labelled fenced block, which is how a pasted text is read. */
function fenced(label: string, content: string): string {
  const body = content.replace(/\n$/, '');
  const lines = body === '' ? 1 : body.split('\n').length;
  return `${label} (lines 1-${lines}):\n\`\`\`\n${body}\n\`\`\``;
}

/**
 * What an attachment is, read off the tag first.
 *
 * The tag is what the host wrote the file as, which is the type the bytes are
 * actually in; what the client said is next, and a file's own name is the last
 * thing that can say - a `screenshot.png` nobody described is a PNG.
 */
const typeFor = (one: Bag, path: string): string => {
  const tag = bag(bag(one._meta)[SNAPSHOT_TAG]);
  if (typeof tag.contentType === 'string' && tag.contentType !== '') return tag.contentType;
  if (typeof one.contentType === 'string' && one.contentType !== '') return one.contentType;
  return IMAGE_EXTENSIONS[extname(path).toLowerCase()] ?? '';
};

/**
 * Whether a type is one that is inlined rather than named by path.
 *
 * Text of every kind, the three applications that are text without saying so,
 * and the `+json` and `+xml` suffixes every other text type is built on - but
 * nothing that says `image/`, since an SVG is markup that draws itself and a
 * picture is what the model is being sent an image for. A picture of a kind
 * the provider will not take is named by path, as any other file is.
 */
const isTextual = (type: string): boolean => {
  if (type.startsWith('image/')) return false;
  return type.startsWith('text/')
    || ['application/json', 'application/xml', 'application/javascript', 'application/typescript'].includes(type)
    || type.endsWith('+json')
    || type.endsWith('+xml');
};

/** Whether this host wrote the file for this message. */
const isSnapshot = (one: Bag): boolean => bag(bag(one._meta)[SNAPSHOT_TAG]).isSnapshot === true;

/** Where a selection starts, as a person counts lines. */
const selectionOf = (one: Bag): string => {
  const line = bag(bag(bag(one.selection).range).start).line;
  return typeof line === 'number' ? `:${line + 1}` : '';
};

/** What a person called the attachment, or a name for one that has none. */
const labelOf = (one: Bag): string =>
  (typeof one.label === 'string' && one.label !== '' ? one.label : 'attachment');

/** One value as an object, for reading fields off something untyped. */
const bag = (value: unknown): Bag => (typeof value === 'object' && value !== null ? value as Bag : {});
