import { mkdtempSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { expect, it } from 'vitest';
import { SNAPSHOT_TAG } from '@ahpd/sdk';
import type { Bag, MessageAttachment } from '@ahpd/sdk';
import { fakePi, opened } from './fake-pi.js';

/*
 * A pi turn reads its message's attachments.
 *
 * The host writes what a client pasted to a file and the message names the
 * path - decision `an-attachments-bytes-are-written-to-disk-and-the-message-
 * names-the-file` - and `partsOf` decides what each attachment is. pi takes one
 * text and a list of images, so what this backend adds is the split: the parts
 * that are text are joined into the one prompt, and an image part becomes the
 * `ImageContent` pi sends beside it.
 *
 * A message with no attachments is the plain text it always was, which is every
 * ordinary turn and every message this host writes itself.
 */

/**
 * Let a run finish.
 *
 * `partsOf` reads real bytes off the disk, so a turn here settles over a few
 * turns of the event loop rather than on the first one.
 */
const until = async (check: () => boolean, times = 2000): Promise<void> => {
  for (let i = 0; i < times; i++) {
    if (check()) return;
    await new Promise((done) => { setTimeout(done, 0); });
  }
};

/** What the fake pi was asked to prompt, in the order it was asked. */
const prompts = (pi: ReturnType<typeof fakePi>): Bag[] => pi.asked.filter((one) => one.kind === 'prompt');

/** A folder of real files, because a part's bytes are read off disk. */
const folder = mkdtempSync(join(tmpdir(), 'ahpd-pi-attach-'));

const wrote = (name: string, bytes: Buffer | string): string => {
  const path = join(folder, name);
  writeFileSync(path, bytes);
  return path;
};

/** A PNG's first bytes. Nothing here decodes it, so a header is a picture. */
const PNG = Buffer.from('89504e470d0a1a0a0000000d49484452000000010000000108060000001f15c489', 'hex');

const IMAGE_LIMIT = 5 * 1024 * 1024;
const TEXT_LIMIT = 64 * 1024;

const smallImage = wrote('small.png', PNG);
const largeImage = wrote('large.png', Buffer.alloc(IMAGE_LIMIT + 1, 7));
const note = wrote('note.txt', 'one\ntwo\n');
const pasted = wrote('pasted.txt', 'x'.repeat(TEXT_LIMIT));
const longText = wrote('long.txt', 'x'.repeat(TEXT_LIMIT + 1));
const picked = wrote('picked.txt', 'mine\n');

/**
 * An attachment as a client sends it.
 *
 * The protocol declares its variants as a `const enum`, whose members name
 * themselves as words but are not values anything imports, so a test writes the
 * word and this is where it becomes the type the session is handed.
 */
const carried = (one: Bag): MessageAttachment => one as unknown as MessageAttachment;

/** A file the host wrote for this message, as host 68 rewrites one. */
const written = (path: string, label: string, contentType: string): MessageAttachment => carried({
  type: 'resource',
  uri: `file://${path}`,
  label,
  contentType,
  _meta: { [SNAPSHOT_TAG]: { isSnapshot: true, contentType } },
});

/** A file somebody picked, which nothing wrote for this message. */
const existing = (path: string, label: string, contentType: string): MessageAttachment => carried({
  type: 'resource',
  uri: `file://${path}`,
  label,
  contentType,
});

/** The one reference block, which names what is not sent as its own part. */
const references = (...lines: string[]): string => [
  'The user provided the following references:',
  ...lines.map((one) => `- ${one}`),
].join('\n');

/** The note a snapshot carries in the reference block. */
const READ_ONLY = '(read-only snapshot, do not edit this file)';

const image = (type = 'image/png'): Bag => ({
  type: 'image',
  data: PNG.toString('base64'),
  mimeType: type,
});

it('prompts a message with no attachments with the plain text it always was', async () => {
  const { session, pi } = opened();
  session.begin('t1', 'what is this');
  await until(() => prompts(pi).length === 1);
  expect(prompts(pi)).toEqual([{ kind: 'prompt', text: 'what is this', images: [] }]);
});

it('sends a pasted image as pi\'s own image, and one too large by path', async () => {
  const { session, pi } = opened();
  session.begin('t1', 'look', undefined, undefined, [
    written(smallImage, 'small.png', 'image/png'),
    written(largeImage, 'large.png', 'image/png'),
  ]);
  await until(() => prompts(pi).length === 1);

  // pi takes one text, so the message and the reference block are one prompt
  // with a blank line between them, and the picture rides beside it.
  expect(prompts(pi)).toEqual([{
    kind: 'prompt',
    text: ['look', references(`${largeImage} ${READ_ONLY}`)].join('\n\n'),
    images: [image()],
  }]);
});

it('inlines a pasted text up to 64 KiB and names what is larger', async () => {
  const { session, pi } = opened();
  session.begin('t1', 'read this', undefined, undefined, [
    written(note, 'note.txt', 'text/plain'),
    written(longText, 'long.txt', 'text/plain'),
  ]);
  await until(() => prompts(pi).length === 1);

  expect(prompts(pi)).toEqual([{
    kind: 'prompt',
    text: [
      'read this',
      'note.txt (lines 1-2):\n```\none\ntwo\n```',
      references(`${longText} ${READ_ONLY}`),
    ].join('\n\n'),
    images: [],
  }]);
});

it('inlines a text of exactly the limit, which is the largest one that fits', async () => {
  const { session, pi } = opened();
  session.begin('t1', 'read this', undefined, undefined, [written(pasted, 'pasted.txt', 'text/plain')]);
  await until(() => prompts(pi).length === 1);
  expect(prompts(pi)).toEqual([{
    kind: 'prompt',
    text: `read this\n\npasted.txt (lines 1-1):\n\`\`\`\n${'x'.repeat(TEXT_LIMIT)}\n\`\`\``,
    images: [],
  }]);
});

it('names a file somebody picked, which is one they work in rather than paste', async () => {
  const { session, pi } = opened();
  session.begin('t1', 'look at this', undefined, undefined, [existing(picked, 'picked.txt', 'text/plain')]);
  await until(() => prompts(pi).length === 1);
  // Small and textual, and still named: only a file this host wrote is the
  // message's own, and a copy of somebody's buffer is not what they attached.
  expect(prompts(pi)).toEqual([{
    kind: 'prompt',
    text: ['look at this', references(picked)].join('\n\n'),
    images: [],
  }]);
});

it('names an image by path when the model takes none', async () => {
  const { session, pi } = opened();
  pi.noImages();
  session.begin('t1', 'look', undefined, undefined, [written(smallImage, 'small.png', 'image/png')]);
  await until(() => prompts(pi).length === 1);

  // Never sent to a model that would refuse it: the turn fails on a picture
  // the provider will not take, and the conversation keeps it for the next one.
  expect(prompts(pi)).toEqual([{
    kind: 'prompt',
    text: ['look', references(`${smallImage} ${READ_ONLY}`)].join('\n\n'),
    images: [],
  }]);
});

it('steers the running turn with its pasted image', async () => {
  const { session, pi } = opened();
  pi.hold();
  session.begin('t1', 'first');
  await until(() => prompts(pi).length === 1);
  expect(session.steer?.('t1', 'actually', [written(smallImage, 'small.png', 'image/png')])).toBe(true);
  await until(() => pi.asked.some((one) => one.kind === 'steer'));

  expect(pi.asked.find((one) => one.kind === 'steer'))
    .toEqual({ kind: 'steer', text: 'actually', images: [image()] });
});

it('sends a queued message with its image when its turn comes', async () => {
  const { session, pi } = opened();
  pi.hold();
  session.begin('t1', 'first');
  await until(() => prompts(pi).length === 1);
  session.queue('q1', 'second', undefined, undefined, [written(smallImage, 'small.png', 'image/png')]);
  // Waiting, so only the first turn has reached pi.
  expect(prompts(pi).map((one) => one.text)).toEqual(['first']);

  pi.raise({ type: 'agent_settled' });
  await until(() => prompts(pi).length === 2);
  expect(prompts(pi)).toEqual([
    { kind: 'prompt', text: 'first', images: [] },
    { kind: 'prompt', text: 'second', images: [image()] },
  ]);
});

it('keeps a queued message\'s attachments where a client reads them waiting', async () => {
  const { session, pi } = opened();
  pi.hold();
  session.begin('t1', 'first');
  await until(() => prompts(pi).length === 1);
  const one = written(smallImage, 'small.png', 'image/png');
  session.queue('q1', 'second', undefined, undefined, [one]);

  // What `chat/pendingMessageSet` echoed, which is the chip a client draws
  // while the message waits.
  const held = (session.chatState().queuedMessages as Bag[])[0] as Bag;
  expect((held.message as Bag).attachments).toEqual([one]);
});

it('keeps a turn\'s attachments on the message the turn was accepted with', async () => {
  const { session, pi, last } = opened();
  const one = written(smallImage, 'small.png', 'image/png');
  session.begin('t1', 'look', undefined, undefined, [one]);
  await until(() => prompts(pi).length === 1);
  expect((last('chat/turnStarted')?.message as Bag).attachments).toEqual([one]);
});
